### ISSUE TITLE
gpu-dawn: Add CI

### ISSUE THREAD

**Issue by iddev5** [hexops/mach#143]
gpu-dawn is currently in a buildable state and as a result it needs to be checked regularly.
This was brought up in #142 and noticed in #139

**Comment by slimsag** [comment]
Yes, definitely CI is needed. It's just been low on priority list compared to other improvements to this package (Windows support, #124 and #121)

One reason it's not as simple as just flipping the switch: Dawn build times are still in multiple minutes, don't want to have to wait that long for every pull request we have to unrelated code.

Ideally, it runs if there were changes to `mach/gpu-dawn` only. Not sure yet how to achieve that with GitHub Actions.

Another option is that, since `mach/gpu-dawn` will be published to github.com/hexops/mach-gpu-dawn as a separate repo in the near future, we can just have CI run there. That's not as good, because it means PRs to it in this repo won't be tested, but better than what we have today for sure.

**Comment by slimsag** [comment]
This looks decent: https://github.com/tj-actions/changed-files

Think we'd just need to write the if condition, something like:

```
if: steps.changed-files.outputs.any_changed == 'true' || steps.changed-files.outputs.any_modified == 'true' || steps.changed-files.outputs.any_deleted == 'true'
```

And add a step:

```
      - name: Check for changes to gpu-dawn
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0
        with:
          files: gpu-dawn/.*
```
